from flask import Flask, render_template, redirect, url_for, request
from flask_bootstrap import Bootstrap5
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy import Integer, String, Float
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FloatField
from wtforms.validators import DataRequired
from dotenv import load_dotenv
import os
import requests

'''
Red underlines? Install the required packages first: 
Open the Terminal in PyCharm (bottom left). 

On Windows type:
python -m pip install -r requirements.txt

On MacOS type:
pip3 install -r requirements.txt

This will install the packages from requirements.txt for this project.
'''

# ---------------------------------------------------------------------------
# ENVIRONMENT SETUP & CONFIGURATION
# ---------------------------------------------------------------------------
# load_dotenv() reads the hidden .env file so we can securely access API keys
# without hardcoding them into the script (which is a major security risk).
load_dotenv()

# Retrieve API credentials and secret keys from the environment variables
bearer_token = os.getenv("API_READ_ACCESS_TOKEN")
api_endpoint = os.getenv("API_ENDPOINT")

# Pre-package the Authorization header for TMDB API requests
Authentication_headers = {"Authorization": f"Bearer {bearer_token}"}

# Initialize the core Flask application
app = Flask(__name__)
app.config['SECRET_KEY'] = os.getenv("SECRET_KEY")

# Wrap the Flask app in Bootstrap5 to automatically style our HTML and WTForms
Bootstrap5(app)

# ---------------------------------------------------------------------------
# DATABASE ARCHITECTURE
# ---------------------------------------------------------------------------
# Configure the SQLite database file path relative to the project directory
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///Top-10-Movies.db'


# Define the declarative base class which all our database models will inherit from
class Base(DeclarativeBase):
    pass


# Initialize the SQLAlchemy extension using our Base class and bind it to the Flask app
db = SQLAlchemy(model_class=Base)
db.init_app(app)


# --- THE MOVIE TABLE MODEL ---
class Movie(db.Model):
    """
    Represents the 'movie' table in the SQLite database.
    Each property defines a specific column type and constraint.
    """
    # Primary Key: A unique integer auto-generated by SQLite for every new row
    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    title: Mapped[str] = mapped_column(String(250), nullable=False)
    year: Mapped[int] = mapped_column(Integer, nullable=False)
    description: Mapped[str] = mapped_column(String(250), nullable=False)
    rating: Mapped[float] = mapped_column(Float, nullable=False)

    # ranking is nullable=True so we can initialize movies with 'None'
    # before our sorting algorithm dynamically calculates their true rank.
    ranking: Mapped[int] = mapped_column(Integer, nullable=True)

    review: Mapped[str] = mapped_column(String(250), nullable=False)
    img_url: Mapped[str] = mapped_column(String(500), nullable=False)


# Ensure the database and tables actually exist before the app runs requests.
# The app_context() is required because db.create_all() needs to know which Flask app it belongs to.
with app.app_context():
    db.create_all()


# ---------------------------------------------------------------------------
# WTFORMS DEFINITIONS
# ---------------------------------------------------------------------------
class RateMovieForm(FlaskForm):
    """Form used on the Edit page to update a movie's rating and review."""
    # DataRequired() ensures the user cannot submit an empty string/null value
    rating = FloatField("Your Rating Out of 10 (e.g. 7.5)", validators=[DataRequired()])
    review = StringField("Your Review", validators=[DataRequired()])
    submit = SubmitField("Done")


class AddMovieForm(FlaskForm):
    """Form used on the Add page to search for a movie title via the TMDB API."""
    title = StringField("Movie Title", validators=[DataRequired()])
    submit = SubmitField("Add Movie")


# ---------------------------------------------------------------------------
# ROUTING & CONTROLLERS
# ---------------------------------------------------------------------------

@app.route("/")
def home():
    """
    Renders the homepage.
    Dynamically sorts all movies by user rating and updates their official ranking
    in the database in real-time before displaying them.
    """
    # 1. Fetch all movies from the database, ordered from highest rating to lowest.
    result = db.session.execute(db.select(Movie).order_by(Movie.rating.desc()))
    all_movies = result.scalars().all()

    # 2. Loop through the sorted list and assign the official ranking.
    # The highest-rated movie (index 0) gets rank 1, the next gets rank 2, etc.
    for i in range(len(all_movies)):
        all_movies[i].ranking = i + 1

    # 3. Commit the newly calculated rankings to the database.
    db.session.commit()

    # 4. Pass the sorted, ranked list to the HTML template for rendering.
    return render_template("index.html", movie_list=all_movies)


@app.route("/edit/<int:id>", methods=["GET", "POST"])
def edit(id):
    """
    Handles updating a movie's rating and review.
    Uses a dynamic URL path variable to target the specific movie ID.
    """
    # Fetch the movie object. If the ID is invalid, safely throw a 404 error instead of crashing.
    movie = db.get_or_404(Movie, id)

    # Initialize the WTForm. Setting obj=movie pre-populates the input fields
    # with the existing database values so the user sees what they are editing.
    form = RateMovieForm(obj=movie)

    # POST METHOD BRANCH: Triggered when the user hits the "Done" submit button
    if form.validate_on_submit():
        # .populate_obj() is a WTForms shortcut that automatically maps the submitted
        # form data back to the corresponding columns in the SQLAlchemy movie object.
        form.populate_obj(movie)

        # Lock the changes into the database
        db.session.commit()

        # Return the user back to the homepage
        return redirect(url_for("home"))

    # GET METHOD BRANCH: Triggered on initial load. Renders the form.
    return render_template("edit.html", form=form, movie=movie)


@app.route("/delete/<int:id>", methods=["POST"])
def delete(id):
    """
    Deletes a specific movie from the database.
    Restricted entirely to POST requests to prevent accidental deletions via standard web crawlers.
    """
    # Locate the target record
    movie_to_delete = db.get_or_404(Movie, id)

    # Stage the object for deletion and execute the commit
    db.session.delete(movie_to_delete)
    db.session.commit()

    return redirect(url_for("home"))


@app.route("/add", methods=["GET", "POST"])
def add():
    """
    Handles the primary movie search interface.
    Accepts GET requests to render the search form, and POST requests to query the TMDB API.
    """
    add_form = AddMovieForm()

    # POST METHOD BRANCH: Triggered when the user submits a search query
    if add_form.validate_on_submit():
        # Package the WTForm text input into the URL query parameters
        query_params = {
            "query": add_form.title.data
        }

        # Fire the GET request to the external TMDB API securely using headers
        response = requests.get(api_endpoint, params=query_params, headers=Authentication_headers)
        data = response.json()

        # TMDB returns a complex dictionary. We extract only the list of movies stored under "results".
        api_results = data["results"]

        # Abandon the add.html template and render the selection interface instead
        return render_template("select.html", options=api_results)

    # GET METHOD BRANCH: Render the standard search form
    return render_template("add.html", form=add_form)


@app.route("/insert", methods=["POST"])
def insert_movie():
    """
    Intercepts the hidden POST form submission from select.html.
    Creates a new database row using the API payload without making a secondary API call.
    """
    # 1. Catch the hidden form data sent from the standard HTML form
    title = request.form.get("title")
    date = request.form.get("date")
    overview = request.form.get("overview")
    poster_path = request.form.get("poster_path")

    # 2. Extract just the year from the YYYY-MM-DD date format.
    # Fallback to "N/A" if TMDB returns an empty date string.
    year = date.split("-")[0] if date else "N/A"

    # 3. Create the Database Object with default placeholders for the user-generated fields
    new_movie = Movie(
        title=title,
        year=year,
        description=overview,
        img_url=f"https://image.tmdb.org/t/p/w500{poster_path}",  # Construct the full TMDB image URL
        rating=0.0,
        ranking=None,
        review="None"
    )

    # 4. Save the object to the database so SQLite generates the new permanent ID
    db.session.add(new_movie)
    db.session.commit()

    # 5. Immediately bounce the user into the edit route using the brand new ID
    return redirect(url_for("edit", id=new_movie.id))


if __name__ == '__main__':
    # Launch the development server
    app.run(debug=True)